New tags styles
domnikl/statsd-php pull request #74
Opened 2020-09-17 15:47 UTC by Karsonito

Hi!
Current version supports only dogstatsd (datadog) tags style.
I needed other styles, so I added them: graphite, Infxdb (telegraf), signalfx, librato

2020-09-17 17:28 UTC, Karsonito commented
I seems that github check uses different psalm.xml config or psalm version.
I have no errors in local machine.
```
composer require --dev vimeo/psalm ^3.4

[karson@centos statsd]$ vendor/bin/psalm -v
Psalm 3.x-dev@d03e5ef057d6adc656c0ff7e166c50b73b4f48f3
[karson@centos statsd]$ vendor/bin/psalm
Scanning files...
Analyzing files...


------------------------------
No errors found!
------------------------------

Checks took 3.07 seconds and used 61.903MB of memory
No files analyzed
```

2020-09-30 19:27 UTC, domnikl commented
Hi @Karsonito and thanks for the PR! 
I just checked and the problems also exist on the master branch, but I definitely get them with the version requested in `composer.json` which resolves to psalm 3.16. You are using a development version, which might be a problem. Also on your output, there is 'No files analyzed' in the last line.
Please bear with me, I will first fix the problems on master and then review your PR :)

2020-10-25 18:43 UTC, domnikl requested changes
Thanks for the PR @Karsonito! If you care to implement the changes, I would be happy to merge it.

2020-10-25 18:43 UTC, domnikl commented on src/Client.php
> +    public function setTagsStyle(string $tagsStyle): void
Changing the tags style after creating the client bears a lot of problems: what if there is a batch running currently and some metrics use the old style and some use the new style?

2020-10-25 18:43 UTC, domnikl commented on src/Client.php
> +    public function getTagsStyle(): string
I don't think there is a real need for this getter.

2020-10-25 18:43 UTC, domnikl commented on src/Client.php
> +    private const TAGS_STYLE_FORMAT = [
There is a feeling in me that these should all be classes instead of configs in this array. When using an interface for TagStyleFormatters, this could easily be implemented by anyone adding tag styles outside of this library for whatever reason they like. Plus, there wouldn't be an implicit contract on individual array keys, which is always a source for possible bugs.

2020-10-25 18:43 UTC, domnikl commented on src/Client.php
> +    private const TAGS_STYLE_FORMAT = [
Also the tests could be way more specific on these.

2021-02-28 21:18 UTC, closed without merging